# Generated by Django 4.0.5 on 2022-07-08 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CuponModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.CharField(max_length=35)),
                ('price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('quantity', models.BigIntegerField(default=1)),
            ],
            options={
                'db_table': 'meli_cupon',
            },
        ),
    ]
